apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-tevn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-tevn
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-tevn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-tevn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-tevn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-npyv-tenant/nodejs-users/simple-nodejs-app-tevn@sha256:781162460fcd4cc6b11ad07baac6b782f89cb27bed11d83103fefb726eedd394
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
